DataDog/docker-dd-agent

Dockerfile
unfortunately, only by 8 MB or so...
=> make for a slightly smaller image

examples/kafka/Dockerfile
=> [Examples] Fix Kafka example

README.md, entrypoint.sh
To be merged during the 5.8 release process
=> Update entrypoint and documentation for service discovery

README.md
document the options introduced by https://github.com/DataDog/docker-dd-agent/pull/86
=> Document "DD_" prefix env variables

entrypoint.sh
=> Fix PROXY_PASSWORD in entrypoint

Dockerfile, alpine/Dockerfile
=> Bump agent to 5.8.5

alpine/entrypoint.sh, entrypoint.sh
As suggested by @Yanivro this is a much more reliable way to get the host ip.
=> [mesos_slave] Replace host ip extraction logic with $HOST

Dockerfile, alpine/Dockerfile, dogstatsd/alpine/Dockerfile
- Reorder the environment variable creations to make the release job easier.
- Merge 2 `ENV` statements in the root dockerfile to remove a layer.
Laziness is my motivation. Script all the things!
=> Update dockerfiles formatting for the release script

README.md, dogstatsd/README.md
Update documentation to fix inconsistencies and improve layout.
Fix #126
=> Refresh READMEs 

alpine/entrypoint.sh
Improve alpine entrypoint formatting. It was done earlier for the Debian one, so let's replicate it here.
=> [formatting] improve alpine entrypoint formatting

alpine/entrypoint.sh
The option already exists in the debian-based image, let's replicate it here.
=> Add consul token option to alpine image

Dockerfile
=> point to beta temporarily while merged agent is unreleased

dogstatsd/README.md
fix document
I pulled deprecated image
=> fix image name for dogstatsd

alpine/entrypoint.sh
Check configs are located under a different path in alpine.
Missed that in my #141 review 🙈
=> [alpine] fix k8s check config file path

alpine/entrypoint.sh, dogstatsd/alpine/entrypoint.sh, dogstatsd/entrypoint.sh, jmx/entrypoint.sh
Adds support for DD_API_KEY_FILE in all entrypoints.
Docker Swarm secret support.
=> Support DD_API_KEY_FILE in all images

README.md
* s/service discovery/Autodiscovery
* mention the `latest-jmx` image
* some clarifications in the DogStatsD section
=> [README] misc clarifications

Dockerfile, Dockerfile-alpine, entrypoint.sh, probe-alpine.sh, probe.sh
=> unexpose supervisor web ui

Dockerfile-dogstatsd, Dockerfile-jmx
=> improve dogstatsd and jmx images healthchecks

Dockerfile-alpine, Dockerfile-dogstatsd-alpine
=> Bump alpine version

CHANGELOG.md
Introduce a changelog in the repo
Improving visibility
=> Introduce repository changelog

Dockerfile
Bumps to 5.21.0-rc.1
5.21.0-rc.1 beta release
=> [beta] bumping to 5.21.0-rc.1

Dockerfile
=> [beta] bumping to 5.22.0-rc.1

Dockerfile-dogstatsd, entrypoint-dogstatsd.sh, entrypoint.sh
Fix supervisor interaction when passing by sysvinit
status command for docker is broken
=> [debian] fix status command

CHANGELOG.md, config_builder.py
Fix a typo in config_builder, update changelog
Fix #296 
=> fix typo, update changelog

README.md
add a  link to the agent6 dockerfiles
Customers asking where to find the agent6 dockerfile.
=> add link to agent6 dockerfiles

Dockerfile
=> beta 5.26.0-rc.1

CHANGELOG.md
=> update changelog for 12.7.5271 release

Dockerfile-rhel
=> Update Dockerfile-rhel with 5.32.8-1
