- README.md
The example is broken because it should be port 8125, over UDP. The README currently has a typo for one example and doesn't specify UDP anywhere
> Fix port typo

- README.md
- entrypoint.sh
I've Added the `dd_url` param to the ENV variables. 
That way we can set it to use an other agent as a proxy ([DOC](https://github.com/DataDog/dd-agent/wiki/Proxy-Configuration#using-the-agent-as-a-proxy))
I did also updated the `Readme.md` according to the change, feel free to update the text to make it more clear.
> Added 'dd_url' param to the ENV variables

- Dockerfile
- entrypoint.sh
Hi,
This is a proof of concept, let me know what you think.
The idea is to be able to mount a volume containing some additional config instead of having to build another Docker image on top of yours.
> Add support for adding yaml files in conf.d without rebuilding a Docker image

- README.md
- entrypoint.sh
To not break anyone who is currently using /conf.d I used the same approach for /checks.d.   It would be cleaner in my opinion to have 1 directory like /opt/docker-dd-agent that get's mounted into the container at /docker-dd-agent and the entrypoint script looks for /docker-dd-agent/conf.d/*yaml and /docker-dd-agent/checks.d/*py and copies them to their proper location.
Let me know if you want me to do change it so only one mountpoint is required on the docker container.
> This patch resolves #53

- Dockerfile
Standalone dogstatsd functionality has been broken since we moved builds to Omnibus 4 (`dogstatsd` executable was not symlinked as required). I added a symlink step in the Dockerfile and this patch is available under the `standalone-dogstatsd` tag for those who want to use it immediately. I stood up this PR in case we want to keep this functionality for future releases.
There were a couple of candidates for where to actually specify the symlink (`entrypoint.sh` v/s `Dockerfile`). In the end I specified it in the Dockerfile since that seemed the first place people would look to check what we're doing with the filesystem.
> Symlink dogstatsd in Dockerfile

- Dockerfile
In support of issue #53 it would be consistent to create the /checks.d directory in the Dockerfile as suggested by user @bradobro.
> Create the checks.d directory in the image

- entrypoint.sh
urls will have the / character, so use a different delimiter. Also,
use single quotes because the interpolation doesnt work
> fix sed of DD_URL

- entrypoint.sh
This way, one could use the regular `datadog/docker-dd-agent` container (without the need to build it with custom configuration) and still configure a `statsd_metric_namespace`.
> Allow to inject statsd_metric_namespace via env variable

- Dockerfile
I noticed two unused lines in your Dockerfile. They're both being overridden by the last `CMD` line in the file. In this case, I'd bet the author meant to use `RUN` instead.
```Dockerfile
...
CMD mkdir -p /conf.d
CMD mkdir -p /checks.d
...
CMD ["supervisord", "-n", "-c", "/etc/dd-agent/supervisor.conf"]
```
See the following excerpt from the [Docker Docs](https://docs.docker.com/engine/reference/builder/#cmd):
>Note: don’t confuse `RUN` with `CMD`. `RUN` actually runs a command and commits the result; `CMD` does not execute anything at build time, but specifies the intended command for the image. 
And since you're using `VOLUME` on the next line, those actually create the directory if needed. If you weren't using volumes, these lines would need to be changed to `RUN`, but since you are, …
> Remove unused CMD lines from Dockerfile

- dd-agent.service
In systemd the `After` directive will only ensure execution ordering of
the specified units if they happen to be started at the same time, but
it does not specify a dependency relation.
`Requires=docker.service` will make sure docker is up and running before
attempting to run the commands of this service.
Signed-off-by: Petros Angelatos <petrosagg@gmail.com>
> ensure docker is running when trying to run the datadog service

- entrypoint.sh
We want to use the datadog image in elasticbeanstalk environments.  When used in this method, environment variables are set globally for all containers.  Using an environment variable name of `API_KEY` could cause some serious clashes with other containers.
By allowing for alternate environment variables `DD_API_KEY`, `DD_TAGS` and `DD_LOG_LEVEL` this ensures that we don't end up with any conflicts.  The original ENV vars still work and exist, so this should not break backwards compatibility.
> Namespace ENV vars.

- README.md
- entrypoint.sh
This PR adds support for enabling "collect_ec2_tags" on the agent using an environment variable.
> Add EC2_TAGS option (collect_ec2_tags)

- entrypoint.sh
Requested often as the docker run `-h` flag isn't taken into account by dd-agent's `get_hostname` function.
> Add a DD_HOSTNAME env variable

- alpine/entrypoint.sh
This option was present in the debian based image, adding it to the alpine one.
> Add DD_HOSTNAME env var to alpine entrypoint

- Dockerfile
- README.md
- alpine/conf.d/docker_daemon.yaml
- alpine/entrypoint.sh
- conf.d/docker_daemon.yaml
- entrypoint.sh
We're refactoring the image tags to try and only have a handful of them. Thus using environment variables to enable checks instead of a separate tag (`mesos` in this case).
This PR makes it possible to enable the mesos slave and master checks through env variables, as well as the marathon and zookeeper ones. It basically updates the work of @alq666 in the branch `alq666/mesos` and integrates it in master.
It will be followed by a PR in the dcos universe repo to update the datadog task.
> Add Mesos monitoring to default tag

- Dockerfile
- README.md
- alpine/entrypoint.sh
- entrypoint.sh
To get rid of the kubernetes image and branch. This is part of the effort of reducing the number of different images we provide and merge them into a single one (or a few ones if necessary), controlled with environment variables.
- Add the option to pass a `KUBERNETES` environment variable that will enable the kubernetes check if set
- Modify supervisor.conf to expose supervisord on `0.0.0.0:9001` when mesos or kubernetes checks are enabled (both for alpine and debian based images)
- Now the alpine-based image can be used too! (making `pullPolicy: Always` less painful)
> Support kubernetes check on main images

- alpine/entrypoint.sh
- entrypoint.sh
datadog.conf layout was recently improved, making #100 necessary, but we still need to support older `datadog.conf` until https://github.com/DataDog/dd-agent/pull/2618 is released in version 5.9.0. This commit can be reverted once 5.9 is out.
Thank you @fotinakis for reporting this issue.
> Add retro-compatibility in entrypoint for older datadog.conf

- alpine/entrypoint.sh
- entrypoint.sh
in some setups, using the hostname from `docker info` doesn't work resolve to the host internal IP, so we fallback to the default gateway in this case.
> use docker info or default gateway to guess host address

- dogstatsd/Dockerfile
- dogstatsd/README.md
- dogstatsd/alpine/Dockerfile
- dogstatsd/alpine/entrypoint.sh
- dogstatsd/alpine/supervisor.conf
- dogstatsd/entrypoint.sh
- dogstatsd/supervisor.conf
To make it possible to run a dogstatsd server container with a non-root user.
This PR make it possible to build a dogstatsd only image. It is based on the (deprecated) https://github.com/DataDog/docker-dogstatsd repository with a few updates. It also runs the server as user id 1001. We don't use a username because it doesn't guarantee that the user is not modified in the dockerfile or entrypoint to effectively be root, so some platforms won't allow it to run for security reasons.
- fixes https://github.com/DataDog/docker-dd-agent/issues/79
> Add dogstatsd image definition in dogstatsd folder

- README.md
This PR adds a note to the section on using dogstatsd only to say that it is not running the collector and thus will not observe the tags that are defined in the config.
I have seen a customer have trouble with the dogstatsd option because they expected tags and labels to be observed (https://hangops.slack.com/archives/datadog/p1473727086000014). Ilan told me there are others as well.
N/A
N/A
> clarify readme around dogstatsd option and tags

- Dockerfile
- entrypoint.sh
This PR is the first step towards providing a separate image to run a standalone dogstatsd server. 
The goal being to allow users to run a dogstatsd server container as a non-root user, and avoid mounting `/proc`, `/sys` and the docker socket just for running dogstatsd
- #79 
- #97
> Deprecation warning for DOGSTATSD_ONLY

- README.md
Formatting to make the README a bit more readable to see what the docker commands are doing. 
Also, I updated the (I believe old) mount points in the standalone section from `/proc/mounts:/host/proc/mounts:ro` --> `/proc/:/host/proc/:ro`
> Update readme, format docker run commands

- alpine/entrypoint.sh
- entrypoint.sh
If the env var `KUBERNETES_COLLECT_EVENTS` is passed we set the `collect_events` config value to `True`.
> Provide env var to activate k8s event collector

- entrypoint.sh
Was fixed on master but not backported to the `kubernetes` branch,
let's fix it since we've released a kubernetes image with a `5.9.0`
agent
> Update sed command on `tags` of datadog.conf

- README.md
- entrypoint.sh
Allow setting the `non_local_traffic` config option.
This can be especially useful in dockerized environments if you want to report metrics from other containers. Seems like this would be a security risk to enable by default, so I'm leaving it as an opt-in.
Tested on my own docker image.
Not sure if it's worth defaulting this to true?
> Allow setting non_local_traffic: true

- Dockerfile
- alpine/Dockerfile
- dogstatsd/Dockerfile
This PR adds a docker healthcheck to our agent. It will rely on the supervisor output to determine the health of the agent processes.
Starting with docker 1.12, this has been made available and is a very helpful way to determine if your containers are in a sane state. We are also adding support for this in the dd-agent.
I _think_ that `supervisord` having pid 1 in the container means that we don't really need to check for the supervisor itself, because if that process would happen to die, the container would shutdown.
`docker inspect <containername>` should now report the health status in `{ 'State': { 'Health': {...} } }`
as well as creating events when the healthcheck reports the container status: `docker events`.
> [healtcheck] adding healthcheck - based on supervisor output.

- README.md
I was considering building a Docker image extending this one to have environment-selectable `collect_events` behavior, but it turned out `docker-dd-agent` already supports it! This adds documentation to make it easier for the next person to realize the same thing.
> Document the KUBERNETES_COLLECT_EVENTS env var

- README.md
Adds description to README.md for use of the [`KUBERNETES_KUBELET_HOST`](https://github.com/DataDog/dd-agent/pull/3051)  en var. 
See DataDog/dd-agent#3051
> Add documentation for KUBERNETES_KUBELET_HOST

- README.md
- entrypoint.sh
Make it possible to provide the consul_token through an env var.
Also make the readme and entrypoint more readable.
> [SD] Add consul token env var to entrypoint

- Dockerfile
- alpine/entrypoint.sh
- entrypoint.sh
This PR addresses issue #151
Automatically detect EC2 host IP for local consul agent when running in ECS
> Added support for EC2 host IP automatic detection for SD_CONFIG_BACKEND

- alpine/Dockerfile
Add curl as a long-term dependency
curl used to be a build dependency only, but we now use it in the entrypoint so let's keep it.
Fix #156
> [alpine] fix missing curl dependency.

- jmx/Dockerfile
- jmx/conf.d/docker_daemon.yaml
- jmx/examples/apache/Dockerfile
- jmx/examples/apache/apache.yaml
- jmx/examples/complex/Dockerfile
- jmx/examples/complex/datadog.conf
- jmx/examples/kafka/Dockerfile
- jmx/examples/kafka/kafka.yaml
- jmx/examples/mysql/Dockerfile
- jmx/examples/mysql/mysql.yaml
Ship JRE in a jmx flavored tag
jmx integrations need it, and jmx service discovery will soon go out. Also fix #159.
> Add a JMX flavor that ships with a JRE

- alpine/Dockerfile
Fix pycurl import error.
pycurl failed to be imported because the one we install doesn't use openssl as a backend. Setting `PYCURL_SSL_LIBRARY` before running `setup_agent.sh` fixes the issue.
Closes #166
> [alpine] Make sure pycurl is installed with openssl backend

- alpine/entrypoint.sh
Basically if condition fails. It's becase Busybox's sh != sh 3.x
```
+ [[ ]]
+ [[ XXXXXXXXXXXXXXXXXX ]]
+ sed -i -e s/^.*api_key:.*$/api_key: XXXXXXXXXXXXXXXXXX/ /opt/datadog-agent/agent/datadog.conf
+ [[ NAMENAMENAMENAME ]]
+ sed -i -r -e s/^# ?hostname.*$/hostname: NAMENAMENAMENAME/ /opt/datadog-agent/agent/datadog.conf
+ [[ ]]
+ [[ yes ]]
+ sed -i -e s/^# collect_ec2_tags.*$/collect_ec2_tags: yes/ /opt/datadog-agent/agent/datadog.conf
+ [[ os-name:CoreOS,os-version:NNNN.N.0 ]]
+ sed -i -r -e s/^# ?tags:.*$/tags: os-name:CoreOS,os-version:NNNN.N.0/ /opt/datadog-agent/agent/datadog.conf
+ [[ ]]
+ [[ ]]
+ [[ ]]
+ [[ ]]
+ [[ ]]
+ [[ ]]
+ [[ ]]
+ [[ ]]
+ curl --silent http://169.254.169.254/latest/meta-data/local-ipv4 --max-time 1
+ EC2_HOST_IP=NNN.NNN.NNN.NNN
+ [[ ]]
+ [[ ]]
+ [[ ]]
+ [[ …
```
> fix alpine entrypoint

- alpine/Dockerfile
Alpine's default df binary doesn't pick up volumes correctly.
Installing coreutils adds a better version that will make the
disk check usable.
Closes #138 
> [alpine] add coreutils dependency

- Dockerfile
- README.md
- entrypoint.sh
[DO NOT MERGE]
- Ensure trace-agent starts with same hostname as infra agent
- Expose trace-agent ports and bump version
> Add trace-agent to container

- alpine/Dockerfile
A bug in the jenkins job that triggers docker releases removed a slash. Adding it back.
Broken build
> Fix missing slash in dockerfile

- entrypoint.sh
This PR adds the option to send the logs of the agent running in a container to the logs of this container ~~instead of~~ in addition to the agent's log files. It allows for a more direct access of the logs.
This is done by setting the environment variable LOGS_STDOUT to 'yes' when running the docker container with `-e LOGS_STDOUT=yes`.
See this [issue](https://github.com/DataDog/docker-dd-agent/issues/174)
Right now, I only managed to test on my local environment by building my own docker image and running the container with the environment variable set to 'yes'. Following the logs of the container, I saw as expected the logs from the forwarder inside. 
~~I haven't tested if these logs were indeed appearing inside of the logs of kubernetes as requested in the …
> Add option to redirect agent's logs to stdout/stderr to be captured in container's logs

- README.md
Update the readme to enable service discovery in the default commands and link to the service discovery guide.
A lot of users still don't know about this feature and resort to hacks to configure checks in container environments.
> Enable service discovery in autoconf mode by default

- README.md
Document how to enable memory cgroups.
Fixes https://github.com/DataDog/docker-dd-agent/issues/149
Another task to consider would be to add an option to make cgroup checks optional, but this is not a priority as of now.
> [doc] document how to enable memory cgroups

- Dockerfile
- alpine/Dockerfile
- jmx/Dockerfile
Attempts to remove network.yaml.default, but doesn't fail the build if the file is not found. Change should be backward compatible.
Failed alpine build after changes to dd-agent following 5.12.x release. See https://github.com/DataDog/dd-agent/commit/b74d12f63491d4b450ad7927f0b2d04006704d4e.
Built locally.
> [alpine] build will no longer necessarily contain network.yaml.default

- alpine/Dockerfile
- dogstatsd/alpine/Dockerfile
We don't always tag the source install script, so this was only sometimes getting the right one.
AGENT_VERSION can be overridden, as you can see here: https://github.com/DataDog/dd-agent/blob/master/packaging/datadog-agent/source/setup_agent.sh#L48
This means that setting it in the env and then using that in the installer script is preferable to anything else.
> We should always use master source installer

- README.md
point out that trace-agent is not available on alpine images
> doc: add rider for trace on alpine images

- jmx/Dockerfile
Enables `sd_jmx_enable` by default in the jmx image.
Without this auto config is not enabled with JMXFetch, which kind of defeats the purpose of this image :(
Checked that the `sed` works as expected
> [jmx] Enable JMX checks for service discovery by default

- alpine/entrypoint.sh
- entrypoint.sh
- jmx/entrypoint.sh
Enables the Kubernetes Namespace name Regex for event collection in the docker image via environment variables
Make easier to use the DDAgent image for Kubernetes
To be merged after ~5.11 is released; https://github.com/DataDog/dd-agent/milestone/76~ 5.12 is released, https://github.com/DataDog/dd-agent/milestone/79
> Enable k8s event collection based on a namspace name regex

- alpine/Dockerfile
Use tini instead of sh for PID 1 to allow graceful termination of the container.
sh doesn't not pass signals to children. When running in kubernetes terminating a dd-agent container will take as long as the `terminationGracePeriodSeconds` setting which is default of 30s.
tini is commonly used as PID 1 and recommended by the [official images repo](https://github.com/docker-library/official-images#init).
Haven't extensively tested for functionality but I'm still getting metrics in my test env. Also confirmed that container termination is much faster in kubernetes and slightly faster locally with docker.
> [alpine] use tini for pid 1 to allow graceful termination

- entrypoint.sh
This PR adds support for the use of docker swarm secret handling. 
For context: https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images
The plan is to use swarm to manage secrets on my current setup. This allows me to do that 👍
> Added support for swarm secret & API_KEY_FILE

- alpine/entrypoint.sh
- entrypoint.sh
- jmx/entrypoint.sh
bugfix: sed handling of KUBERNETES_NAMESPACE_NAME_REGEX
cant reflect KUBERNETES_NAMESPACE_NAME_REGEX to kubernetes.yaml
> bugfix: KUBERNETES_NAMESPACE_NAME_REGEX

- Dockerfile
- README.md
we're dropping the behavior of binding to the legacy port in https://github.com/DataDog/datadog-trace-agent/pull/271
> doc: curb mentions of legacy trace port 7777

- README.md
- dogstatsd/Dockerfile
- dogstatsd/entrypoint.sh
- dogstatsd/supervisor.conf
This adds the trace-agent program to the dogstatsd supervisor configuration. this allows running the trace-agent as part of the `dogstatsd` only container
When DD_APM_ENABLED=false (the default), the trace-agent will gracefully exit, not affecting the other processes managed by supervisor
should address #199
> add trace-agent to dogstatsd only container

- dogstatsd/entrypoint.sh
- APM env var was always set to false
- copied hostname settings from regular image
fix enable APM in dogstatsd image because env var is currently always set to false
can't use dogstatsd image with APM
> fix enable APM in dogstatsd image

- README.md
- alpine/entrypoint.sh
- entrypoint.sh
- jmx/entrypoint.sh
add SD_JMX_ENABLE and USE_DOGSTATSD env vars
Allows enabling of JMX service discovery and disabling of dogstatsd service.
> add SD_JMX_ENABLE and USE_DOGSTATSD env vars

- alpine/entrypoint.sh
- entrypoint.sh
- jmx/entrypoint.sh
As we inject them with sed with a / delimiter, slashes in tag values led to syntax errors. 
Instead of changing the sed delimiter and risking having the bug on another
character, I used bash parameter expansion to escape them with a \ before sed-ing
See https://www.gnu.org/software/bash/manual/bashref.html#Shell-Parameter-Expansion
Support case
> allow slashes in TAGS/ECS2_TAGS vars by escaping them

- README.md
- alpine/entrypoint.sh
- entrypoint.sh
- jmx/entrypoint.sh
As a follow-up for https://github.com/DataDog/integrations-core/pull/476 and sister PR, allow to disable `kube_service` tagging with an envvar.
All three entrypoints are patched.
> add KUBERNETES_COLLECT_SERVICE_TAGS envvar for kubernetes' collect_service_tags conf

- README.md
- alpine/entrypoint.sh
- entrypoint.sh
- jmx/entrypoint.sh
5.15 introduces the `sd_backend_username` and `sd_backend_password` options (for etcd only for now). This PR introduces envvar bindings to set them.
Users that don't want to send credentials as envvars can create a custom image shipping their own `datadog.conf` file.
> add SD_BACKEND_USER and SD_BACKEND_PASSWORD envvar bindinds for 5.15

- alpine/entrypoint.sh
This PR lets you set either the `LOGS_STDOUT` or `DD_LOGS_STDOUT` env var to `yes` to force the agent's components to log to stdout and stderr, in addition to its normal log file.
This brings STDOUT logging in the Alpine image into feature parity with
the Debian image.
This feature was implemented in the Debian image in https://github.com/DataDog/docker-dd-agent/pull/176.
Running the Alpine docker-dd-agent in Kubernetes it is _much_ easier to access its logs if they go to STDOUT and STDERR.
I've tested this locally by running the container with `-e LOGS_STDOUT=yes` and have seen it work.
> Log to STDOUT/STDERR in Alpine container when LOGS_STDOUT is set

- README.md
- jmx/entrypoint.sh
Mirroring #176 and #220, adds handling of the `DD_LOGS_STDOUT` envvar for the jmx variant. As that envvar was not documented, updated the README too.
> add DD_LOGS_STDOUT handling to jmx variant + documentation

- dogstatsd/Dockerfile
- dogstatsd/alpine/Dockerfile
Tracer agent is using HTTPS connection to Datadog services to push payload, but when ca-certificates package is not installed then it fails during flush giving error as in title. This PR fixes that and allows to push the payload properly
I am playing with APM and found that issue, since it's a quick fix I decided to do a PR
> Fix "x509: failed to load system roots and no roots provided"

- dogstatsd/alpine/entrypoint.sh
- dogstatsd/entrypoint.sh
Add `DD_HOSTNAME` envvar binding to both dsd flavours, as is it is the case with full agent images.
Fixes https://github.com/DataDog/docker-dd-agent/issues/221
> add DD_HOSTNAME envvar binding to both dsd flavours

- alpine/entrypoint.sh
Mitigates a data leak in the alpine docker build caused by enabling xtrace in the entrypoint
Found API tokens in our logstream from this app, figured noone else should suffer the revoke-recreate cycle we're about to :-) 
1. Run the alpine container
2. Expect to not see bash -x output like the below
+ export API_KEY=<ELIDED>
+ [[ <ELIDED> 0]]
+ sed -i -e s/^.*api_key:.*$/api_key: <ELIDED>/ /opt/datadog-agent/agent/datadog.conf
> Do not set -x on entrypoint - it emits the api tokens into logs.

- README.md
- config_builder.py
Fixes `sd_config_backend` and `sd_backend_host` variables that weren't being written to `datadog.conf`
(fixes regression introduced in #222)
Built a custom image with the updated script, seems to fix the issue
Also sneaked in a small fix to the README (`sd_backend_host` for Zookeeper needs to be `zk` instead of `zookeeper`)
> Fix sd_config_backend and sd_backend_host vars

- README.md
- entrypoint.sh
Add `KUBERNETES_LEADER_CANDIDATE` and `KUBERNETES_LEADER_LEASE_DURATION` envvar bindings to entrypoint for 5.17 leader election feature. Update README
Tag `xvello_beta` is being rebuilt with that commit cherry-picked
> envvar bindinds for k8s leader election

- entrypoint.sh
Currently, if you try and use `DD_LOGS_STDOUT` with the alpine image you get the following error from the entrypoint script:
```
Error: The directory named as part of the path 
/dev/stdoutnstdout_logfile_maxbytes=0nstderr_logfile=/dev/stderrnstderr_logfile_maxbytes=0
does not exist. in section ‘program:forwarder’ (file: ‘agent/supervisor.conf’)
```
This is caused by the newlines not being properly interpreted by busybox's `sed` implementation.
> Fix Alpine's LOGS_STDOUT functionality

- entrypoint-dogstatsd.sh
Ports the support of DD_LOGS_STDOUT envvar for the dsd images. Should address the last inconsistency from https://github.com/DataDog/docker-dd-agent/pull/228
Uses the fixed sed invocation from https://github.com/DataDog/docker-dd-agent/pull/234
> port LOGS_STDOUT to dsd images

- README.md
- config_builder.py
- update config_builder.py to allow disabling non-local traffic
- update readme with updated docker run example that disables non-local traffic and explain the consequences of enabling it
security!
> update config_builder and readme about non-local traffic

- Dockerfile-rhel
- rhel/datadog.repo
- rhel/help.1
- rhel/help.md
- rhel/licenses/LICENSE
Add a RHEL7 based container image for dd-agent
Inclusion in Red Hat's [container directory](https://access.redhat.com/containers). 
1) Spin up a RHEL virtual machine.  
2)  docker build . --file=./Dockerfile-rhel 
3) docker run $IMAGE_ID
> Add a RHEL7 based container image for dd-agent

- README.md
- config_builder.py
- entrypoint.sh
Adds the collect_labels_as_tags as an Environment variable:
see https://github.com/DataDog/integrations-core/pull/881
Requested by the community.
Successfully tested locally.
> DD_COLLECT_LABELS_AS_TAGS as an environment variable 

- Dockerfile-dogstatsd-alpine
Add the same healthcheck to the dogstatsd-alpine image as the plain alpine image uses.
I noticed that the only variant of docker-dd-agent that didn't have a healthcheck defined was the variant we are using.
This is a simple change to Dockerfile, so I don't think this section applies.
None
> Add healthcheck to dogstatsd-alpine image

- config_builder.py
adds histogram_percentile and sd_jmx_enable settings via ENV Var to config_builder.py
These settings are not easily configurable in the image currently.
> add HISTOGRAM_PERCENTILES and SD_JMX_ENABLE to config_builder.py

- entrypoint-dogstatsd.sh
- entrypoint.sh
Some linux versions have issues with storing unix sockets in `overlay` volumes, making the healthcheck fail:
- https://github.com/Supervisor/supervisor/issues/654
- https://github.com/moby/moby/issues/12080
This PR moves the sock to `/dev/shm` that is a `tmpfs` as a workaround for these hosts with an affected kernel.
Image `datadog/dev-dd-agent:xvello_sock_in_shm` tested and confirmed by affected user.
> move the supervisord socket to /dev/shm

- entrypoint-dogstatsd.sh
- entrypoint.sh
https://github.com/DataDog/docker-dd-agent/pull/269 moved the supervisord unix socket to `/dev/shm/` instead of the default `/opt/datadog-agent/run/`.
This breaks the [link between the collector and supervisord](https://github.com/DataDog/dd-agent/blob/a8d6a47cf001f9fc7c336c822718fea1e5bf890b/agent.py#L429) for jmxfetch management. This PR fixes it by setting the `supervisor_socket` option in `datadog.conf` so that the collector can communicate with supervisord.
Bug report
> set the supervisor_socket option to fix jmxfetch AD

- README.md
Document the `DD_PROCESS_AGENT_ENABLED` envvar and specify it's not available on alpine (same as APM).
https://github.com/DataDog/docker-dd-agent/issues/260
> document the DD_PROCESS_AGENT_ENABLED envvar

- Dockerfile
- Dockerfile-alpine
- Dockerfile-jmx
- Dockerfile-rhel
The PR [integration-cores #994](https://github.com/DataDog/integrations-core/pull/994) allows to collect some network metrics inside a container.
This PR set the associated configuration to use this new feature.
**Dockerfile:**
```bash
docker run --rm -it -e DD_API_KEY=1234er local /bin/sh -c 'cat /etc/os-release ; cat /etc/dd-agent/datadog.conf ; ls -l /etc/dd-agent/conf.d/network.yaml.default'
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[Main]
dd_url = https://app.datadoghq.com
api_key = 1234er
gce_updated_hostname = yes
non_local_traffic = yes
supervisor_socket = /dev/shm/datadog-supervisor.sock …
```
> Configuration: configure the network check

- README.md
Clarify documentation line
Requested on https://trello.com/c/ckeV5lUf/246-reword-note-on-docker-dd-agent-readme-page
A customer thought that the `DD_` prefix was available on all environment variables.
> clarify documentation line for envvars

- Dockerfile-alpine
- Dockerfile-dogstatsd-alpine
We need `libffi-dev` to `pip install cffi` which is a dependency of our `ssh_check`.
> Adding libffi-dev to alpine images

- README.md
Documentation update, for review
Motivation:
Docker links are legacy: https://docs.docker.com/network/links/
> Move docker links to legacy in dogstatsd section

- CHANGELOG.md
- Dockerfile
- Dockerfile-dogstatsd
- Dockerfile-jmx
The GPG key we use to sign the APT repository has been rotated due to expiration. Update the dockerfiles to trust the new key.
> Update the debian Dockerfile with the new GPG signing key

- README.md
- config_builder.py
- entrypoint.sh
This PR does two things:
* Uncomments the `[trace.sampler]` section in the stock `datadog.conf`
* Adds the `max_traces_per_second` configuration option to `datadog.conf`
This allows a user to configure this value by setting the `MAX_TRACES_PER_SECOND` environment variable.
We are heavy users of APM.  We require a higher `max_traces_per_second` than what the default provides (10).  
The inability to configure `max_traces_per_second` via an environment variable.
> add support for max_traces_per_second option to datadog.conf

- CHANGELOG.md
- Dockerfile
- Dockerfile-dogstatsd
- Dockerfile-jmx
Update the base image for Debian images to stretch, to bring in:
- consistency with agent6 image
- java8 support for latest jboss jar
- longer support (official support for jessie ends June 2018)
Size is in the same ballpark as jessie:
- latest: 150 MB
- xvello_stretch: 149 MB
- latest-jmx: 214 MB
- xvello_stretch_jmx: 203 MB
```
====================
Collector (v 5.22.1)
====================
Status date: 2018-03-02 14:18:39 (3s ago)
Pid: 30
Platform: Linux-4.4.0-112-generic-x86_64-with-debian-9.3
Python Version: 2.7.14, 64bit
Logs: <stderr>, /var/log/datadog/collector.log
Clocks
======
NTP offset: 0.0727 s
System UTC time: 2018-03-02 14:18:43.309019
Paths
=====
conf.d: /etc/dd-agent/conf.d
checks.d: Not found
Hostnames
=========
socket-hostname: 8b45d3384746
hostname: ci-xaviervello …
```
> update to stretch

- Dockerfile-rhel
Restore the build of the rhel image, that is currently failing because of 
> [91mhttps://cdn.redhat.com/content/htb/rhel/server/7/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
HTB: https://access.redhat.com/solutions/513153
We don't pull packages from this repo, might as well disable it
> rhel: disable rhel-7-server-htb-rpms repo

- README.md
Update the Amazon Linux cgroup details: for Amazon Linux 2, it's now standard on `/sys/fs/cgroup` instead of different in `/cgroup`.
Support issue
> [README] Update the Amazon Linux cgroup details 

- README.md
Agent v5 doc was pointing to an agent v6 doc
this https://docs.datadoghq.com/agent/autodiscovery/ (agent 6)
instead of this: https://docs.datadoghq.com/agent/faq/agent-5-autodiscovery/ (agent 5)
> Update link to stay consistent with Agent v5

- Dockerfile-rhel
Update RHEL image to 5.26
Update Docker RHEL image to 5.26.x
> Update RHEL image to 5.26

- README.md
- config_builder.py
Adds `histogram_aggregates` as a configurable setting via config_builder
Updates README to reflect that these ENV variables are something that can be set on image.
This setting isn't configurable currently for 5.x agents , adding this options matches it to what we provide on agent v6. 
> add HISTOGRAM_AGGREGATES to configurable env_variables and config_builder.py

- Dockerfile
- Dockerfile-alpine
- Dockerfile-dogstatsd
- Dockerfile-dogstatsd-alpine
- Dockerfile-jmx
This PR allows build arguments to enable easily building custom images for our agents by parametrizing repository, channel and agent version. We still keep sane defaults.
Improving our QA automation pipeline for docker.
> [docker][cli] add arguments to allow easy custom builds

- Dockerfile-alpine
Specify INTEGRATIONS_VERSION
pipeline fails without this because we get the version in `config.py` which is `5.31.0` which doesn't exist yet.
> Add INTEGRATIONS_VERSION

- README.md
See #364 
Updates the descriptions of the DD_HISTOGRAM_AGGREGATES and DD_HISTOGRAM_PERCENTILES environment variables to state they are comma-separated.
I got bitten by this bug when adding the `sum` aggregate.
> Describe histogram aggregates and percentile configs as comma-separated

- Dockerfile
- Dockerfile-dogstatsd
- Dockerfile-jmx
Updates the docker agent base image to use the more current buster slim
More current, secure base image.
> [base] moving to buster slim

- Dockerfile
- Dockerfile-dogstatsd
- Dockerfile-jmx
Bumps to buster-20200803-slim.
Desirable updates to base images.
> [dockerfile] base: update to buster-20200803-slim
